# Generated by Django 4.2.4 on 2023-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                null=True, related_name="courses", to="tb.student"
            ),
        ),
    ]
