# Generated by Django 4.2.4 on 2023-08-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0003_alter_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course",
                to="tb.teacher",
            ),
        ),
    ]
