# Generated by Django 4.2.4 on 2023-08-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0004_alter_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="time_lecture",
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_lecture", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lectures",
                        to="tb.book",
                    ),
                ),
            ],
        ),
    ]
