# Generated by Django 4.2.4 on 2023-08-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0005_remove_book_time_lecture_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="tb.student",
            ),
        ),
    ]
