# Generated by Django 4.2.4 on 2023-08-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb", "0006_remove_course_students_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                null=True, related_name="courses", to="tb.student"
            ),
        ),
    ]
